### PR TITLE
Feature that lets you play a mp3 at the same time as your song to help copy notes

### PR DESCRIPTION
**Pull request by kidofcubes**
idk about the name, feel free to make any suggestions

### CODE REVIEW

**Comment by chenxi050402** [comment]
idk but have you ever tried doing that when making songs? I think doing that might get you confused about whether the sound is in the song or is a note block and the sound of one might cover the other one. It might be helpful if you're checking if everything in the song matches the original, but that can easily be done by playing them side by side using a music player or just convert the original song into .ogg and make it an instrument.
also why is the indent 8 characters long

**Comment by KidOfCubes** [comment]
which indent

it might not help *that* much for more complex songs, but it makes things a lot easier for me
also i tried doing the playing the original thing but i was pretty bad at it
didnt really consider the making the original song into a instrument to play thing, that prob removes the need for this thingy

**Comment by chenxi050402** [comment]
the code indent
why is your tab 8 spaces instead of 4, looks weird surrounded by 4 space indent codes

**Comment by KidOfCubes** [comment]
image
it looks fine in the editor for some reason

**Comment by chenxi050402** [comment]
maybe it's just github displays tabs 8 characters wide for some reason

**Comment by KidOfCubes** [comment]
ive tried the custom instrument trick, and it really doesnt work well for longer songs, and it seems to have slowed down my music file slightly? could be because of the tempo or smth

im unable to stop the entire song from playing out when it gets triggered, even when i stop the song, and clicking on the icon in the menu starts playing it as well

**Comment by chenxi050402** [comment]
Closing this because this is implemented in another way in 3.12

**Pull request closed without merging**
